"""empty message

Revision ID: 0d25fac9ccd3
Revises: 501196f24285
Create Date: 2020-11-17 16:58:23.264052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d25fac9ccd3'
down_revision = '501196f24285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
