"""empty message

Revision ID: 364e6767bc7f
Revises: 55be17db8908
Create Date: 2020-12-17 11:00:19.026587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '364e6767bc7f'
down_revision = '55be17db8908'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('address', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'address')
    # ### end Alembic commands ###
