"""empty message

Revision ID: 501196f24285
Revises: 70d5cdb7b8b7
Create Date: 2020-11-17 16:54:11.801732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '501196f24285'
down_revision = '70d5cdb7b8b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'past_shows')
    op.drop_column('Artist', 'upcoming_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('upcoming_shows', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('past_shows', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
