"""empty message

Revision ID: 50979deaa3d1
Revises: 0d25fac9ccd3
Create Date: 2020-11-17 16:58:42.114114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50979deaa3d1'
down_revision = '0d25fac9ccd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###
